# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25c52bf9c1687d79ac55c80817c00f373f707de64435a63cc962f31b082293b4786848d1313f449790ab618f66c531a6a2cb70e771a104d8365a5738e760f6fe

test:
  secret_key_base: f8023a5b2b61011e8851bd72dd4ac4ad19584d7f1605e96a807b65784bb8e529bc7f250589e89dc364f5187ccd5453e71b744eb3b1b55b6be5045e9bb9bd8280

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: f9f6400888c90ae5533ffc587b02970a77f1c64b270b2b147936e8c40ecf34c6a2a735ad2e31c83ba6cc2c582d7bfc37ecfd297e3cb28e08f03ccf3de43ea7dc 
# secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
